### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by xingxing2233** [fergaletto/PPE-detector-Tiny-YOLOv3-Rasp.erry-PI-and-NCS2#1]
Hi! Hello! I can't download the model file. Can you send it to my mailbox?

Mailbox：xingxingyukeji@gmail.com

tiny_yolo_IR_500000_FP16.xml
tiny_yolo_IR_500000_FP16.bin
tiny_yolo_IR_500000_FP32.bin
tiny_yolo_IR_500000_FP32.xml

Thank you！

**Comment by fergaletto** [comment]
Hi, i changed the files permits. You should be able to download them now. 

Regards, 
Fernando.
